FROM node:20-alpine AS build
WORKDIR /app

COPY client/package*.json ./
RUN npm install
COPY client .
RUN npm run build

# Serve con vite preview
EXPOSE 4173
CMD ["npm", "run", "preview", "--", "--host", "0.0.0.0", "--port", "4173"]
